apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: proofstack
data:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "proofstack.local"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "proofstack"
  POSTGRES_USER: "proofstack"

  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_BUCKET: "proofstack"
